/*!
 * \file   Type.h
 *
 * \author ZhengYuanQing
 * \date   2019/1/10
 * \email  zhengyuanqing.95@gmail.com
 *
 */
#ifndef __TYPE_H__63E7BFCE_AD18_4AC6_80A0_B76BA2D68A0D
#define __TYPE_H__63E7BFCE_AD18_4AC6_80A0_B76BA2D68A0D

#include "Utils/Handle.hpp"

BEG_XE_NAMESPACE

DECL_PTR( Widget );
DECL_PTR( Layout );
DECL_PTR( UserInterface );

DECL_HANDLE( XE_API, Widget );

enum class Alignment
{
	LEFT = 1 << 0,
	RIGHT = 1 << 1,
	TOP = 1 << 2,
	BOTTOM = 1 << 3,
	HCENTER = 1 << 4,
	VCENTER = 1 << 5,
	CENTER = HCENTER | VCENTER,
	LEFT_TOP = LEFT | TOP,
	RIGHT_TOP = RIGHT | TOP,
	LEFT_CENTER = LEFT | HCENTER,
	RIGHT_CENTER = RIGHT | HCENTER,
	LEFT_BOTTOM = LEFT | BOTTOM,
	RIGHT_BOTTOM = RIGHT | BOTTOM,
	TOP_CENTER = TOP | VCENTER,
	BOTTOM_CENTER = BOTTOM | VCENTER,
};
DECL_META_ENUM( XE_API, Alignment );

enum class Orientation
{
	VERTICAL = 1 << 0,
	HORIZONTAL = 1 << 1,
	OMNIDIRECTIONAL = VERTICAL | HORIZONTAL,
};
DECL_META_ENUM( XE_API, Orientation );

enum class SizePolicy
{
	IGNORED,
	FIXED,
	MINIMUM,
	MAXIMUM,
	PREFERRED,
	EXPANDING,
	MINIMUMEXPANDING,
};
DECL_META_ENUM( XE_API, SizePolicy );

enum class SizeConstraint
{
	NO_CONSTRAINT,
	FIXED_SIZE,
	MINIMUM_SIZE,
	MAXIMUM_SIZE,
	MIN_AND_MAX_SIZE,
};
DECL_META_ENUM( XE_API, SizeConstraint );


END_XE_NAMESPACE

#endif // __TYPE_H__63E7BFCE_AD18_4AC6_80A0_B76BA2D68A0D
