/*!
 * \file    Type.h
 *
 * \author  ZhengYuanQing
 * \date    2019-05-15
 * \email   zhengyuanqing.95@gmail.com
 *
 */
#ifndef __TYPE_H__6580A518_948A_4162_A63F_E02DCC393EC9
#define __TYPE_H__6580A518_948A_4162_A63F_E02DCC393EC9

#include "Global.h"

BEG_XE_NAMESPACE

DECL_PTR( IRenderContext );

DECL_HANDLE( RHI_API, Uniform );
DECL_HANDLE( RHI_API, VertexLayout );

DECL_HANDLE( RHI_API, FrameBuffer );
DECL_HANDLE( RHI_API, IndexBuffer );
DECL_HANDLE( RHI_API, VertexBuffer );
DECL_HANDLE( RHI_API, ComputeBuffer );
DECL_HANDLE( RHI_API, IndirectBuffer );
DECL_HANDLE( RHI_API, InstanceBuffer );
DECL_HANDLE( RHI_API, DepthStencilBuffer );
DECL_HANDLE( RHI_API, DynamicIndexBuffer );
DECL_HANDLE( RHI_API, DynamicVertexBuffer );

DECL_HANDLE( RHI_API, Shader );

DECL_HANDLE( RHI_API, BlendState );
DECL_HANDLE( RHI_API, RasterizerState );
DECL_HANDLE( RHI_API, DepthStencilState );
DECL_HANDLE( RHI_API, ComputePipelineState );
DECL_HANDLE( RHI_API, GraphicsPipelineState );

DECL_HANDLE( RHI_API, Texture );

DECL_HANDLE( RHI_API, TimerQuery );
DECL_HANDLE( RHI_API, OcclusionQuery );

DECL_HANDLE( RHI_API, CommandList );


enum class FillType
{
	WIRTEFRAME,
	SOLID,
};
DECL_META_ENUM( RHI_API, FillType );

enum class CullType
{
	NONE,
	FRONT,
	BACK,
};
DECL_META_ENUM( RHI_API, CullType );

enum class TopologyType
{
	UNDEFINED,
	POINTLIST,
	LINELIST,
	LINESTRIP,
	TRIANGLELIST,
	TRIANGLESTRIP,
	LINELIST_ADJ,
	LINESTRIP_ADJ,
	TRIANGLELIST_ADJ,
	TRIANGLESTRIP_ADJ,
	CONTROL_POINT_PATCHLIST_01,
	CONTROL_POINT_PATCHLIST_02,
	CONTROL_POINT_PATCHLIST_03,
	CONTROL_POINT_PATCHLIST_04,
	CONTROL_POINT_PATCHLIST_05,
	CONTROL_POINT_PATCHLIST_06,
	CONTROL_POINT_PATCHLIST_07,
	CONTROL_POINT_PATCHLIST_08,
	CONTROL_POINT_PATCHLIST_09,
	CONTROL_POINT_PATCHLIST_10,
	CONTROL_POINT_PATCHLIST_11,
	CONTROL_POINT_PATCHLIST_12,
	CONTROL_POINT_PATCHLIST_13,
	CONTROL_POINT_PATCHLIST_14,
	CONTROL_POINT_PATCHLIST_15,
	CONTROL_POINT_PATCHLIST_16,
	CONTROL_POINT_PATCHLIST_17,
	CONTROL_POINT_PATCHLIST_18,
	CONTROL_POINT_PATCHLIST_19,
	CONTROL_POINT_PATCHLIST_20,
	CONTROL_POINT_PATCHLIST_21,
	CONTROL_POINT_PATCHLIST_22,
	CONTROL_POINT_PATCHLIST_23,
	CONTROL_POINT_PATCHLIST_24,
	CONTROL_POINT_PATCHLIST_25,
	CONTROL_POINT_PATCHLIST_26,
	CONTROL_POINT_PATCHLIST_27,
	CONTROL_POINT_PATCHLIST_28,
	CONTROL_POINT_PATCHLIST_29,
	CONTROL_POINT_PATCHLIST_30,
	CONTROL_POINT_PATCHLIST_31,
	CONTROL_POINT_PATCHLIST_32,
};
DECL_META_ENUM( RHI_API, TopologyType );

enum class AccessType
{
	NONE = 0,
	READ,
	WIRTE,
	READWIRTE,
};
DECL_META_ENUM( RHI_API, AccessType );

enum class BackbufferRatio
{
	EQUAL,     //!< Equal to backbuffer.
	HALF,      //!< One half size of backbuffer.
	QUARTER,   //!< One quarter size of backbuffer.
	EIGHTH,    //!< One eighth size of backbuffer.
	SIXTEENTH, //!< One sixteenth size of backbuffer.
	DOUBLE,    //!< Double size of backbuffer.
};
DECL_META_ENUM( RHI_API, BackbufferRatio );

enum class CompareType
{
	LESS,
	LEQUAL,
	EQUAL,
	GEQUAL,
	GREATER,
	NOTEQUAL,
	NEVER,
	ALWAYS,
};
DECL_META_ENUM( RHI_API, CompareType );

enum class AttributeType
{
	INT8,
	INT16,
	INT32,
	INT64,
	UINT8,
	UINT16,
	UINT32,
	UINT64,
	FLOAT16,
	FLOAT32,
	FLOAT64,
};
DECL_META_ENUM( RHI_API, AttributeType );

enum class RenderContextType
{
	EMPTY,
	METAL,
	VULKAN,
	OPENGL,
	OPENGLES2,
	OPENGLES3,
	DIRECT3D11,
	DIRECT3D12,
};
DECL_META_ENUM( RHI_API, RenderContextType );

enum class UniformType
{
	VEC4,
	MAT3,
	MAT4,
	SAMPLER,
	TEXTURE,
};
DECL_META_ENUM( RHI_API, UniformType );

enum class TextureType
{
	TEXTURE1D,
	TEXTURE2D,
	TEXTURE3D,
	TEXTURECUBE,
	TEXTURE2DARRAY,
};
DECL_META_ENUM( RHI_API, TextureType );

enum class TextureFormat
{
	///       RGBA16S
	///       ^   ^ ^
	///       |   | +-- [ ]unorm
	///       |   |     [F]float
	///       |   |     [S]snorm
	///       |   |     [I]int
	///       |   |     [U]uint
	///       |   +---- Number of bits per component
	///       +-------- Components

	BC1,          /// DXT1
	BC2,          /// DXT3
	BC3,          /// DXT5
	BC4,          /// LATC1/ATI1
	BC5,          /// LATC2/ATI2
	BC6H,         /// BC6H
	BC7,          /// BC7
	ETC1,         /// ETC1 RGB8
	ETC2,         /// ETC2 RGB8
	ETC2A,        /// ETC2 RGBA8
	ETC2A1,       /// ETC2 RGB8A1
	PTC12,        /// PVRTC1 RGB 2BPP
	PTC14,        /// PVRTC1 RGB 4BPP
	PTC12A,       /// PVRTC1 RGBA 2BPP
	PTC14A,       /// PVRTC1 RGBA 4BPP
	PTC22,        /// PVRTC2 RGBA 2BPP
	PTC24,        /// PVRTC2 RGBA 4BPP
	ATC,          /// ATC RGB 4BPP
	ATCE,         /// ATCE RGBA 8 BPP explicit alpha
	ATCI,         /// ATCI RGBA 8 BPP interpolated alpha
	ASTC4x4,      /// ASTC 4x4 8.0 BPP
	ASTC5x5,      /// ASTC 5x5 5.12 BPP
	ASTC6x6,      /// ASTC 6x6 3.56 BPP
	ASTC8x5,      /// ASTC 8x5 3.20 BPP
	ASTC8x6,      /// ASTC 8x6 2.67 BPP
	ASTC10x5,     /// ASTC 10x5 2.56 BPP

	UNKNOWN,      /// Compressed formats above.

	R1,
	A8,
	R8,
	R8I,
	R8U,
	R8S,
	R16,
	R16I,
	R16U,
	R16F,
	R16S,
	R32I,
	R32U,
	R32F,
	RG8,
	RG8I,
	RG8U,
	RG8S,
	RG16,
	RG16I,
	RG16U,
	RG16F,
	RG16S,
	RG32I,
	RG32U,
	RG32F,
	RGB8,
	RGB8I,
	RGB8U,
	RGB8S,
	RGB9E5F,
	BGRA8,
	RGBA8,
	RGBA8I,
	RGBA8U,
	RGBA8S,
	RGBA16,
	RGBA16I,
	RGBA16U,
	RGBA16F,
	RGBA16S,
	RGBA32I,
	RGBA32U,
	RGBA32F,
	R5G6B5,
	RGBA4,
	RGB5A1,
	RGB10A2,
	RG11B10F,

	UNKNOWN_DEPTH, /// Depth formats below.

	D16,
	D24,
	D24S8,
	D32,
	D16F,
	D24F,
	D32F,
	D0S8,
};
DECL_META_ENUM( RHI_API, TextureFormat );

enum class SamplerFilter
{
	MIN_MAG_MIP_POINT = 0,
	MIN_MAG_POINT_MIP_LINEAR = 0x1,
	MIN_POINT_MAG_LINEAR_MIP_POINT = 0x4,
	MIN_POINT_MAG_MIP_LINEAR = 0x5,
	MIN_LINEAR_MAG_MIP_POINT = 0x10,
	MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x11,
	MIN_MAG_LINEAR_MIP_POINT = 0x14,
	MIN_MAG_MIP_LINEAR = 0x15,
	ANISOTROPIC = 0x55,
	COMPARISON_MIN_MAG_MIP_POINT = 0x80,
	COMPARISON_MIN_MAG_POINT_MIP_LINEAR = 0x81,
	COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x84,
	COMPARISON_MIN_POINT_MAG_MIP_LINEAR = 0x85,
	COMPARISON_MIN_LINEAR_MAG_MIP_POINT = 0x90,
	COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x91,
	COMPARISON_MIN_MAG_LINEAR_MIP_POINT = 0x94,
	COMPARISON_MIN_MAG_MIP_LINEAR = 0x95,
	COMPARISON_ANISOTROPIC = 0xd5,
	MINIMUM_MIN_MAG_MIP_POINT = 0x100,
	MINIMUM_MIN_MAG_POINT_MIP_LINEAR = 0x101,
	MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x104,
	MINIMUM_MIN_POINT_MAG_MIP_LINEAR = 0x105,
	MINIMUM_MIN_LINEAR_MAG_MIP_POINT = 0x110,
	MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x111,
	MINIMUM_MIN_MAG_LINEAR_MIP_POINT = 0x114,
	MINIMUM_MIN_MAG_MIP_LINEAR = 0x115,
	MINIMUM_ANISOTROPIC = 0x155,
	MAXIMUM_MIN_MAG_MIP_POINT = 0x180,
	MAXIMUM_MIN_MAG_POINT_MIP_LINEAR = 0x181,
	MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x184,
	MAXIMUM_MIN_POINT_MAG_MIP_LINEAR = 0x185,
	MAXIMUM_MIN_LINEAR_MAG_MIP_POINT = 0x190,
	MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x191,
	MAXIMUM_MIN_MAG_LINEAR_MIP_POINT = 0x194,
	MAXIMUM_MIN_MAG_MIP_LINEAR = 0x195,
	MAXIMUM_ANISOTROPIC = 0x1d5
};
DECL_META_ENUM( RHI_API, SamplerFilter );

enum class SamplerAddress
{
	U_MIRROR	= 1 << 0,
	U_CLAMP		= 1 << 1,
	U_BORDER	= 1 << 2,
	
	V_MIRROR	= 1 << 3,
	V_CLAMP		= 1 << 4,
	V_BORDER	= 1 << 5,
	
	W_MIRROR	= 1 << 6,
	W_CLAMP		= 1 << 7,
	W_BORDER	= 1 << 8,
	
	UVW_MIRROR	= U_MIRROR | V_MIRROR | W_MIRROR,
	UVW_CLAMP	= U_CLAMP | V_CLAMP | W_CLAMP,
	UVW_BORDER	= U_BORDER | V_BORDER | W_BORDER,
};
DECL_META_ENUM( RHI_API, SamplerAddress );

enum class BlendFactor
{
	ZERO,
	ONE,
	SRC_COLOR,
	INV_SRC_COLOR,
	SRC_ALPHA,
	INV_SRC_ALPHA,
	DST_ALPHA,
	INV_DST_ALPHA,
	DST_COLOR,
	INV_DST_COLOR,
	SRC_ALPHA_SAT,
	FACTOR,
	INV_FACTOR,
};
DECL_META_ENUM( RHI_API, BlendFactor );

enum class BlendOperation
{
	ADD,
	SUB,
	REVSUB,
	MIN,
	MAX,
};
DECL_META_ENUM( RHI_API, BlendOperation );

enum class StencilOperation
{
	ZERO,
	KEEP,
	REPLACE,
	INCR,
	INCRSAT,
	DECR,
	DECRSAT,
	INVERT,
};
DECL_META_ENUM( RHI_API, StencilOperation );

enum class ClearType
{
	CLEAR_COLOR,
	CLAER_DEPTH,
	CLAER_STENCIL,
	CLAER_COLOR_DEPTH,
	CLAER_COLOR_STENCIL,
	CLAER_DEPTH_STENCIL,
	CLAER_COLOR_DEPTH_STENCIL,
};
DECL_META_ENUM( RHI_API, ClearType );

enum CommandListType
{
	DIRECT,
	BUNDLE,
	COMPUTE,
	COPY,
	VIDEO_DECODE,
	VIDEO_PROCESS,
};
DECL_META_ENUM( RHI_API, CommandListType );

END_XE_NAMESPACE

#endif //__TYPE_H__6580A518_948A_4162_A63F_E02DCC393EC9
